"""NEAR mechanism for x402 payment protocol."""

from .constants import (
    DEFAULT_DECIMALS,
    ERR_AMOUNT_MISMATCH,
    ERR_ARGS_DECODE_FAILED,
    ERR_BLOCK_FETCH_FAILED,
    ERR_DUPLICATE_SETTLEMENT,
    ERR_INVALID_NONCE,
    ERR_INVALID_PAYLOAD_MISSING_FIELDS,
    ERR_INVALID_SENDER_ID,
    ERR_INVALID_TX_HASH,
    ERR_NETWORK_MISMATCH,
    ERR_NONCE_MISMATCH,
    ERR_RECIPIENT_MISMATCH,
    ERR_SIGNER_MISMATCH,
    ERR_TOKEN_CONTRACT_MISMATCH,
    ERR_TRANSACTION_EXPIRED,
    ERR_TRANSACTION_FAILED,
    ERR_TRANSACTION_NOT_FOUND,
    ERR_UNEXPECTED_ACTIONS,
    ERR_UNSUPPORTED_SCHEME,
    ERR_WRONG_METHOD,
    FT_TRANSFER_DEPOSIT,
    FT_TRANSFER_GAS,
    NEAR_ACCOUNT_ID_REGEX,
    NEAR_MAINNET_CAIP2,
    NEAR_MAINNET_RPC_URL,
    NEAR_TESTNET_CAIP2,
    NEAR_TESTNET_RPC_URL,
    NEAR_TX_HASH_REGEX,
    NONCE_HEX_REGEX,
    SCHEME_EXACT,
    SETTLEMENT_TTL_SECONDS,
    USDC_MAINNET_ADDRESS,
    USDC_TESTNET_ADDRESS,
)
from .settlement_cache import SettlementCache
from .signer import ClientNearSigner, FacilitatorNearSigner
from .types import ExactNearPayload, FtTransferArgs
from .utils import (
    convert_to_usdc_units,
    get_rpc_url,
    get_usdc_address,
    parse_money_to_decimal,
    validate_near_account_id,
    validate_near_tx_hash,
    validate_nonce,
)

__all__ = [
    # Constants
    "SCHEME_EXACT",
    "DEFAULT_DECIMALS",
    "NEAR_MAINNET_RPC_URL",
    "NEAR_TESTNET_RPC_URL",
    "USDC_MAINNET_ADDRESS",
    "USDC_TESTNET_ADDRESS",
    "NEAR_MAINNET_CAIP2",
    "NEAR_TESTNET_CAIP2",
    "FT_TRANSFER_GAS",
    "FT_TRANSFER_DEPOSIT",
    "SETTLEMENT_TTL_SECONDS",
    "NEAR_ACCOUNT_ID_REGEX",
    "NEAR_TX_HASH_REGEX",
    "NONCE_HEX_REGEX",
    # Error codes
    "ERR_UNSUPPORTED_SCHEME",
    "ERR_NETWORK_MISMATCH",
    "ERR_INVALID_PAYLOAD_MISSING_FIELDS",
    "ERR_INVALID_TX_HASH",
    "ERR_INVALID_SENDER_ID",
    "ERR_INVALID_NONCE",
    "ERR_TRANSACTION_NOT_FOUND",
    "ERR_TRANSACTION_FAILED",
    "ERR_SIGNER_MISMATCH",
    "ERR_TOKEN_CONTRACT_MISMATCH",
    "ERR_UNEXPECTED_ACTIONS",
    "ERR_WRONG_METHOD",
    "ERR_ARGS_DECODE_FAILED",
    "ERR_RECIPIENT_MISMATCH",
    "ERR_AMOUNT_MISMATCH",
    "ERR_NONCE_MISMATCH",
    "ERR_TRANSACTION_EXPIRED",
    "ERR_BLOCK_FETCH_FAILED",
    "ERR_DUPLICATE_SETTLEMENT",
    # Types
    "ExactNearPayload",
    "FtTransferArgs",
    # Settlement cache
    "SettlementCache",
    # Signer protocols
    "ClientNearSigner",
    "FacilitatorNearSigner",
    # Utilities
    "get_rpc_url",
    "get_usdc_address",
    "convert_to_usdc_units",
    "parse_money_to_decimal",
    "validate_near_account_id",
    "validate_near_tx_hash",
    "validate_nonce",
]
